# Generated by Django 6.0.4 on 2026-04-19 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('plant_start_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('plant_end_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('harvest_start_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('harvest_end_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('min_temp_c', models.SmallIntegerField(blank=True, help_text='Rough minimum safe temp for planting (C)', null=True)),
                ('max_temp_c', models.SmallIntegerField(blank=True, help_text='Rough heat stress threshold (C)', null=True)),
                ('rain_sensitive', models.BooleanField(default=False, help_text='If true, heavy rain windows reduce planting score')),
                ('growing_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='advisor.growingzone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshot', to='advisor.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_links', to='advisor.crop')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crops', to='advisor.farmerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'crop'), name='unique_farmer_crop')],
            },
        ),
    ]
