# Generated by Django 6.0.4 on 2026-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='advisory_preference',
            field=models.CharField(blank=True, choices=[('both', 'Both Planting & Harvest'), ('planting', 'Planting Only'), ('harvest', 'Harvest Only')], help_text='Which advisory type the farmer wants to receive. Null = not yet chosen.', max_length=16, null=True),
        ),
    ]
